server:

  port: 8080
  ssl:
       enabled: true
       key-store: classpath:localhost.p12
       key-store-type: PKCS12
       key-store-password: changeit
       key-password: changeit

spring:

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pilates
    username: durmaz
    password: snopydog_33
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 832470061525-lt5hijl9f86j9m4ar8ot98uc4kvfr00k.apps.googleusercontent.com
            client-secret: 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
            #spring.security.oauth2.client.registration.google.client-secret=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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 637113034824477
            clientSecret: 963ceb5315148f60c27573ca8888ec4a
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
          instagram:
            client-id: 637113034824477
            client-secret: 963ceb5315148f60c27573ca8888ec4a
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
      resource:
       userInfoUri: https://graph.facebook.com/me